baseurl = "/"
languageCode = "en-us"
title = "I'm Che Jinying"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme = "smol"
paginate = 5
copyright = "jinying-che"

# Parameters
[params]
    subtitle = "Your blog subtitle goes here!"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 2 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 3 


  [[menu.footer]]
        name = "Github"
        url = "https://github.com/jinying-che"
        weight = 1 
