baseURL = "https://jinying-che.github.io/"
title = "I'm Che Jinying"
theme = "anatole"
languagecode = "en-us"
defaultcontentlanguage = "en"

[params]
    author = "Che Jinying"
	title = "I'm Jinying"
    info = "Gopher and Vimer"
    description = "Call me nobody"
	profilePicture = "images/me.jpg"
	contentratio = 0.8

# Social links
[[params.socialIcons]]
    title = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jinying-che/"
[[params.socialIcons]]
    title = "instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 2
    url = "https://www.instagram.com/jinying.che/"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "manni"
    tabWidth = 2
