name: Deploy Hugo to VPS 

on:
  push:
    branches: [ "main" ]

env:
  RELEASE_DIR_BASE: /var/www/site/releases

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync public/ to new release dir on VPS
        run: |
          REL="${{ env.RELEASE_DIR_BASE }}/${{ github.sha }}"
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p $REL"
          rsync -avz --delete \
            -e "ssh -p ${{ secrets.VPS_PORT }}" \
            public/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:$REL/

      - name: Flip symlink and reload nginx
        env:
          NGINX_ACTION: ${{ secrets.NGINX_ACTION || 'reload' }}
        run: |
          REL="${{ env.RELEASE_DIR_BASE }}/${{ github.sha }}"
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "ln -sfn $REL /var/www/site/current && sudo systemctl $NGINX_ACTION nginx"

      - name: Cleanup old releases (keep last 5)
        run: |
          ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            'cd /var/www/site/releases && ls -1t | tail -n +6 | xargs -r rm -rf'

